site_name: GraphV - Graph Viewer Library
site_description: GraphV - Graph Viewer Library
site_url: https://github.com/py4mac/graphql-plotly-viewer

theme:
  name: "material"
  palette:
    primary: "teal"
    accent: "amber"
  logo: "img/icon-white.svg"
  favicon: "img/favicon.png"

repo_name: github.com/py4mac/graphql-plotly-viewer
repo_url: https://github.com/py4mac/graphql-plotly-viewer
edit_uri: ""

nav:
  - Graphv: "index.md"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
